services:
  12-factor-app:
    build:
      context: .
      dockerfile: Dockerfile  # This is your FastAPI Dockerfile
    container_name: 12_factor_app
    ports:
      - "9000:9000"  # Expose FastAPI
    volumes:
      - .:/app       # Optional: mount code for live-reloading in dev
    env_file:
      - .env
    restart: unless-stopped

  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: mkdocs_app
    volumes:
      - ./docs:/docs
    working_dir: /docs
    command: serve --dev-addr=0.0.0.0:8001
    ports:
      - "8001:8001"
    restart: unless-stopped
